markdown: kramdown

title: FLX Groove
email: flxgroove@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  FLX Groove is a team of electronic dance music DJs in the Central and Southern
  Tier regions of upstate NY. We are a fully-equipped team, available to play parties
  and events, big and small.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://flxgroove.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Google Analytics
# google-analytics: TBA

# SCSS
sass:
  sass_dir: _scss
  style: :compressed

# Compress
compress_html:
  clippings: all

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Defaults
defaults:
  -
    scope:
      type: 'events'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
